### ISSUE TITLE
'file' not defined in utils.py

### ISSUE THREAD

**Issue by anupamme** [TalLinzen/rnn_agreement#1]
I tried using following the model:

from rnnagr.agreement_acceptor import InflectVerb
pvn = InflectVerb(filenames.deps, prop_train=0.1)

But it throws error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/rnn_agreement/rnnagr/agreement_acceptor.py", line 153, in __init__
    self.inflect_verb, _ = gen_inflect_from_vocab(self.vocab_file)
  File "/home/ubuntu/rnn_agreement/rnnagr/utils.py", line 88, in gen_inflect_from_vocab
    for line in file(vocab_file):
NameError: name 'file' is not defined

I am using python 3.5 (I used 2to3 to convert the code) on ubuntu. Can you tell me why this issue is coming?

Thanks

**Comment by TalLinzen** [comment]
As far as I can tell this is indeed a Python 2 vs. 3 issue - the "file" object has been removed in Python 3. Replacing "file" with "open" should fix it.

**Comment by anupamme** [comment]
Yes, changing file to open fixes it.
